### PR TITLE
Fixes #135: Adding merge-scripts option.

### LINKED ISSUE #135: Allow "scripts" key to be merged
This is a feature request. 

As a user of composer-merge-plugin, I would like to define `scripts` in my composer includes and merge them into my root composer.json by setting `merge-scripts` to `true`.

### PR DESCRIPTION
**Pull request by grasmash**
This allows the 'scripts' section of a composer.json file to be merged via the merge plugin.

### CODE REVIEW

**Comment by grasmash** [comment]
Looks like all but the PHP7 tests are passing, and that appears to be failing due to an issue with Travis. Likely related to the current S3 outage.

**Comment by grasmash** [comment]
@legoktm Please let me know if you have any suggestions or edits. Thank you!

**Comment by bd808** [comment]
The implementation here looks technically correct, but I don't think that it actually has any effect on the Composer runtime. I haven't traced through all of the Composer codebase to figure out exactly why, but local testing with a `composer.local.json` like the one below shows none of the expected `echo` commands being run. This may be a problem similar to the one in #62 where we aren't actually getting a reference to the real `CompletePackage` that Composer is using to resolve scripts.
 
```
{
    "scripts": {
        "pre-install-cmd": "echo pre-install-cmd",
        "post-install-cmd": "echo post-install-cmd",
        "pre-update-cmd": "echo pre-update-cmd",
        "post-update-cmd": "echo post-update-cmd",
        "post-status-cmd": "echo post-status-cmd",
        "pre-archive-cmd": "echo pre-archive-cmd",
        "post-archive-cmd": "echo post-archive-cmd",
        "pre-autoload-dump": "echo pre-autoload-dump",
        "post-autoload-dump": "echo post-autoload-dump",
        "post-root-package-install": "echo post-root-package-install",
        "post-create-project-cmd": "echo post-create-project-cmd",
        "pre-dependencies-solving": "echo pre-dependencies-solving",
        "post-dependencies-solving": "echo post-dependencies-solving",
        "pre-package-install": "echo pre-package-install",
        "post-package-install": "echo post-package-install",
        "pre-package-update": "echo pre-package-update",
        "post-package-update": "echo post-package-update",
        "pre-package-uninstall": "echo pre-package-uninstall",
        "post-package-uninstall": "echo post-package-uninstall",
        "command": "echo command",
        "pre-file-download": "echo pre-file-download"
    }
}
```

**Comment by grasmash** [comment]
Fudge. Ok, I will look into this. Thank you for the review!

**Comment by bd808** [comment]
Note to self: when testing features with feature flags, make sure you have the feature flag enabled. :/

@grasmash I think I sent you down a rabbit hole with my prior comment. Once I actually added a `"merge-scripts": true` setting the fundamentals of this work as expected.

**Comment by grasmash** [comment]
Yay! And thanks for the update ... I was fully in that rabbit hole at that moment.

**Comment by grasmash** [comment]
Out of curiosity, is there a planned release date for 1.4.0?

**Comment by bd808** [comment]
> Out of curiosity, is there a planned release date for 1.4.0?

I think I meant to release it a couple of months ago and forgot. Let's say "soon" and see if I actually get it done in a reasonable amount of time.

**Comment by grasmash** [comment]
I'll note that I found one small issue here. If you define a custom script named `command` you may run `composer run-script command` and it works as expected. However, the shortcut `composer command` does not work.

**Comment by bd808** [comment]
>> Out of curiosity, is there a planned release date for 1.4.0?
> I think I meant to release it a couple of months ago and forgot. Let's say "soon" and see if I actually get it done in a reasonable amount of time.

`{{done}}` -- https://packagist.org/packages/wikimedia/composer-merge-plugin#v1.4.0

**Pull request merged**
