### PR TITLE
Updating Travis CI and Scrutinizer yaml files.

### PR DESCRIPTION
**Pull request by arcanedev-maroc**

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
@bd808 did you use a shared config in Scrutinizer ??

**Comment by bd808** [comment]
> @bd808 did you use a shared (global) config in Scrutinizer ??

No, the project is not configured using a shared config. Current configuration shown in the Scrutinizer gui:
```
tools:
    external_code_coverage:
        timeout: 1200
        runs: 3
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src','tests']
    php_cpd:
        enabled: true
        excluded_dirs: ['vendor', 'tests', 'example']
    php_loc:
        enabled: true
        excluded_dirs: ['vendor', 'tests', 'example']
    php_pdepend: true
    php_sim: true
    
filter:
    excluded_paths:
        - 'tests/*'

checks:
    php:
        php5_style_constructor: true
        parameters_in_camelcaps: true
        parameter_non_unique: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        optional_parameters_at_the_end: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        avoid_corrupting_byteorder_marks: true
```

**Comment by arcanedev-maroc** [comment]
Ok, the only thing remain is to choose one and not both of them (Keeping `.scrutinizer.yml` config file or the scrutinizer ui config).

**Comment by bd808** [comment]
Replaced by #80

**Pull request closed without merging**
