### PR TITLE
Merge in the autoload sections of merged packages

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes https://github.com/wikimedia/composer-merge-plugin/issues/18

Please note that I have only tested this automatically. It's possible I misunderstood what should happen and thus wrote an incorrect test. Manual testing on a real install before merging is advised.

### CODE REVIEW

**Comment by legoktm** [comment]
When I run `composer update` it looks good (autoload is properly added), but running `composer dump-autoload` gets rid of entries added by the merge plugin. Do we need to listen to a different hook/event for that?

**Comment by JeroenDeDauw** [comment]
> running composer dump-autoload gets rid of entries added by the merge plugin.

Good catch! I did not think of that.

> Do we need to listen to a different hook/event for that?

Probably. I'll look into that soonish.

**Comment by JeroenDeDauw** [comment]
Looks like the event we are looking for `ScriptEvents::PRE_AUTOLOAD_DUMP`. Assuming the documentation is wrong as it seems to be, and it indeed is not deprecated (see https://github.com/composer/composer/pull/4065).

**Comment by JeroenDeDauw** [comment]
I now added handling for that hook and also did a manual verification that

* it did not work without the handler
* it does work with the handler

**Comment by JanZerebecki** [comment]
Wikimedia\Composer\MergePluginTest::testSubscribedEvents is missing the new event, thus fails.

**Comment by JeroenDeDauw** [comment]
Right. CI not set up correctly here, or something glitched. TravisCI indeed failed. https://travis-ci.org/wikimedia/composer-merge-plugin/builds/64107129

**Comment by JeroenDeDauw** [comment]
Tests running locally now.

**Comment by JanZerebecki** [comment]
+1 Looks good.

**Pull request merged**
